### ISSUE TITLE
Missing DLLs or Dependencies when Building

### ISSUE THREAD

**Issue by robert-7** [gambitproject/gambit#208]
# Brief Goal
I've been able to successfully install Gambit. Now, I'd like to use PyInstaller to create an standalone executable for my Python program that uses Gambit (that I set up with [MinGW](http://www.mingw.org/) on Windows 10 x64 with Python 2.7.12). 

# Problem
It seems that I'm missing the DLL files I need to create a standalone executable and I'm not certain how to find the ones I'm missing. I've tried using some tools [mentioned here](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly), but I'm hitting dead-ends. I was wondering if someone who understands Gambit more than me would know (or know how to find out) what files I'd need to include and how they'd resolve this.

# More Details / Scenario
I wrote a Python script, `gen_tree_manila_poker.py` that works with Gambit. Now, what I'd like to do is to create a standalone build (a Windows executable that I can share with someone). Now, I installed PyInstaller 3.1.1 (http://pythonhosted.org/PyInstaller/) and I tried running `pyinstaller gen_tree_manila_poker.py`. The build is successful with this output:

```
  $ pyinstaller gen_tree_manila_poker.py
250 INFO: PyInstaller: 3.1.1
250 INFO: Python: 2.7.12
265 INFO: Platform: Windows-10-10.0.14393
343 INFO: wrote c:\Users\Robert\code\github\gambit\src\python\gambit\tests\test_games\personal_test_games\gen_tree_manila_poker.spec
359 INFO: UPX is not available.
608 INFO: Extending PYTHONPATH with paths
['c:\\Users\\Robert\\code\\github\\gambit\\src\\python\\gambit\\tests\\test_games\\personal_test_games',
 'c:\\Users\\Robert\\code\\github\\gambit\\src\\python\\gambit\\tests\\test_games\\personal_test_games']
625 INFO: checking Analysis
641 INFO: Building Analysis because out00-Analysis.toc is non existent
641 INFO: Initializing module dependency graph...
655 INFO: Initializing module graph hooks...
1203 INFO: running Analysis out00-Analysis.toc
1233 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\Python27\python.exe
1828 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
1843 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
2406 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9247_none ...
2500 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35.manifest
2546 INFO: Searching for file msvcr90.dll
2577 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcr90.dll
2577 INFO: Searching for file msvcp90.dll
2608 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcp90.dll
2608 INFO: Searching for file msvcm90.dll
2608 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcm90.dll
3141 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
3141 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
3155 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
3531 INFO: Analyzing c:\Users\Robert\code\github\gambit\src\python\gambit\tests\test_games\personal_test_games\gen_tree_manila_poker.py
10375 INFO: Processing pre-find module path hook   distutils
14707 INFO: Processing pre-safe import module hook   _xmlplus
34593 INFO: Looking for import hooks ...
34657 INFO: Processing hook   hook-distutils.py
34657 INFO: Processing hook   hook-sysconfig.py
34671 INFO: Processing hook   hook-xml.py
35144 INFO: Processing hook   hook-lxml.etree.py
35215 INFO: Processing hook   hook-httplib.py
35223 INFO: Processing hook   hook-pygments.py
44004 INFO: Processing hook   hook-_tkinter.py
44800 INFO: checking Tree
44809 INFO: Building Tree because out00-Tree.toc is non existent
44809 INFO: Building Tree out00-Tree.toc
46116 INFO: checking Tree
46132 INFO: Building Tree because out01-Tree.toc is non existent
46136 INFO: Building Tree out01-Tree.toc
46312 INFO: Processing hook   hook-pkg_resources.py
46327 INFO: Processing hook   hook-encodings.py
56030 INFO: checking Tree
56046 INFO: Building Tree because out02-Tree.toc is non existent
56046 INFO: Building Tree out02-Tree.toc
57847 INFO: checking Tree
57855 INFO: Building Tree because out03-Tree.toc is non existent
57875 INFO: Building Tree out03-Tree.toc
57957 INFO: Looking for ctypes DLLs
58082 INFO: Analyzing run-time hooks ...
58152 INFO: Including run-time hook 'pyi_rth_pkgres.py'
58190 INFO: Including run-time hook 'pyi_rth__tkinter.py'
58323 INFO: Looking for dynamic libraries
60027 INFO: Looking for eggs
60034 INFO: Using Python library C:\Windows\system32\python27.dll
60038 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9247), publicKeyToken=u'1fc8b3b9a1e18e3b')]
60175 INFO: Warnings written to c:\Users\Robert\code\github\gambit\src\python\gambit\tests\test_games\personal_test_games\build\gen_tree_manila_poker\warngen_tree_manila_poker.txt
62188 INFO: checking PYZ
62188 INFO: Building PYZ because out00-PYZ.toc is non existent
62188 INFO: Building PYZ (ZlibArchive) c:\Users\Robert\code\github\gambit\src\python\gambit\tests\test_games\personal_test_games\build\gen_tree_manila_poker\out00-PYZ.pyz
67359 INFO: checking PKG
67375 INFO: Building PKG because out00-PKG.toc is non existent
67383 INFO: Building PKG (CArchive) out00-PKG.pkg
67679 INFO: Bootloader c:\Python27\lib\site-packages\pyinstaller-3.1.1-py2.7.egg\PyInstaller\bootloader\Windows-32bit\run.exe
67691 INFO: checking EXE
67697 INFO: Building EXE because out00-EXE.toc is non existent
67707 INFO: Building EXE from out00-EXE.toc
67738 INFO: Appending archive to EXE c:\Users\Robert\code\github\gambit\src\python\gambit\tests\test_games\personal_test_games\build\gen_tree_manila_poker\gen_tree_manila_poker.exe
68379 INFO: checking COLLECT
68388 INFO: Building COLLECT because out00-COLLECT.toc is non existent
68398 INFO: Building COLLECT out00-COLLECT.toc
68988 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
```

However, if I try to run `gen_tree_manila_poker.exe` in command line, the output is:

```
$ gen_tree_manila_poker.exe
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.1.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "gambit\__init__.py", line 23, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.1.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "gambit\lib\libgambit.py", line 7, in <module>
  File "gambit\lib\libgambit.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified module could not be found.
gen_tree_manila_poker returned -1
```

I ran Dependency Walker and See a bunch of API-MS-WIN-* and EXT-MS-WIN-* DLLs missing. However, this is a [known issue with Dependency Walker](http://stackoverflow.com/questions/36240215/dependency-walker-missing-dlls).

# What I'm Looking For
So yea, I'm not sure what I'm missing. Am I missing the load_module? Am I missing some DLL? Any help would be appreciated?

**Comment by tturocy** [comment]
I'm afraid, as I don't really use Windows, I can't be of any real help here.
