### ISSUE TITLE
Games from arrays with floating point values cause a type error

### ISSUE THREAD

**Issue by Delta-Sigma** [gambitproject/gambit#257]
```
>>> import gambit
>>> import numpy as np
>>> arr = np.array([[1,0,0,0],[0,0.5,0.5,0.5]],dtype=gambit.Rational)
>>> g = gambit.Game.from_arrays(arr, -arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 File "gambit/lib/game.pxi", line 153, in gambit.lib.libgambit.Game.from_arrays
 File "gambit/lib/outcome.pxi", line 98, in gambit.lib.libgambit.Outcome.__setitem__
TypeError: payoff argument should be a numeric type instance
```

I get the same error when using gambit.Decimal type. I do not get the error when all values in the payoff are integers as in the documentation example.

Environment:
MacOS. Python 3.7.5. Gambit 16.0.1 (latest commit as of posting this)

**Comment by tturocy** [comment]
Yes, it is an error.  Gambit requires precisely-specified data for payoffs; floating-point data can never be used.

Can you please show the actual dtypes of the data in the array as created?

**Comment by Delta-Sigma** [comment]
```
In[12]: arr
Out[12]: 
array([[1, 0, 0, 0],
       [0, 0, 0.5, 0.5]], dtype=object)
```
Was this what you meant? Sorry if it wasn't.

I copied the values into another, making each element an instance of gambit.Decimal, like this:
```
arr2 = np.zeros((2,4), dtype=gambit.Decimal)
for r in range(2):
    for c in range(4):
        arr2[r][c] = gambit.Decimal(arr[r][c])
```
And arr2, looks like this:
```
array([[Decimal('1'), Decimal('0'), Decimal('0'), Decimal('0')],
       [Decimal('0'), Decimal('0'), Decimal('0.5'), Decimal('0.5')]],
      dtype=object)
```
I can create the game using this, but I can't use the solver on it:
```
>>> g = gambit.Game.from_arrays(arr2, -arr2)
>>> solver = gambit.nash.ExternalLogitSolver()
>>> solver.solve(g)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-e1c05eda2e26>", line 1, in <module>
    solver.solve(g)
  File "/usr/local/lib/python3.7/site-packages/gambit-16.0.1-py3.7-macosx-10.14-x86_64.egg/gambit/nash.py", line 228, in solve
    return self._parse_output(self.launch(command_line, game),
  File "/usr/local/lib/python3.7/site-packages/gambit-16.0.1-py3.7-macosx-10.14-x86_64.egg/gambit/nash.py", line 54, in launch
    child_stdin.write(game.write(format='native'))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by sylvaticus** [comment]
I think this should deserve a note on the documentation.. I spent several hours trying to pinpoint this problem, not least as there is a reference in the documentation to `pygambit.Decimal`, so like the OP, I thought I could just use decimal values in the array from which to create the game.....
