### ISSUE TITLE
pygambit AttributeError: module 'pygambit' has no attribute 'gameiter'

### ISSUE THREAD

**Issue by manuelmontesinos** [gambitproject/gambit#306]
Related with my [previous intervention](https://github.com/gambitproject/gambit/issues/305), here is another problem that I have found while running the tutorial to the Python interface (code below):

```
Traceback (most recent call last):
  File "C:\Users\user\pygambit_tutorial.py", line 160, in <module>
    print(list(g.contingencies))
  File "pygambit\lib\game.pxi", line 263, in pygambit.lib.libgambit.Game.contingencies.__get__
AttributeError: module 'pygambit' has no attribute 'gameiter'
```

In this case I did get the same error in both Windows and macOS.

```python
# Read a game
g = pygambit.Game.read_game("e02.efg")
print("     Details of a game loaded from efg format:")
print(" ")
print(g)
print("     Players of a game loaded in efg format:")
print(" ")
print(g.players)

# In this game, Player 1 has three strategies and Player 2 has two
print("     Strategies of Player 1:")
print(" ")
print(g.players[0].strategies)
print("     Strategies of Player 2:")
print(" ")
print(g.players[1].strategies)

# The property 'Game.contingencies' is the collection of all the outcomes of the
# game
print("     Possible outcomes of the game:")
print(" ")
print(list(g.contingencies))
```

**Comment by tturocy** [comment]
Fixed in c0fbc7e3.
