### ISSUE TITLE
Bug in code that turns pygambit.Action into string

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#321]
When I print values by typing the following at the REPL:
   g.actions
or
   g.infosets[0].actions

I get:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygambit/lib/libgambit.pyx", line 400, in pygambit.lib.libgambit.Collection.__repr__
  File "pygambit/lib/action.pxi", line 32, in pygambit.lib.libgambit.Action.__repr__
AttributeError: 'pygambit.lib.libgambit.Action' object has no attribute 'player'

It looks like a bug in the code to print out an Action.

**Comment by mdnahas** [comment]
This code worked for me in pygambit/lib/action.pxi

    def __repr__(self):
        return (
            f"<Action [{self.action.deref().GetNumber()-1}] '{self.label}' "
	    f"at infoset '{self.infoset.label}' "
            f"for player '{self.infoset.player.label}' "
            f"in game '{self.infoset.game.title}'>"
        )
